set_property SRC_FILE_INFO {cfile:/home/vivadouser/Projects/not_gate/not_gate.srcs/constrs_1/new/not_constraint.xdc rfile:../../../not_gate.srcs/constrs_1/new/not_constraint.xdc id:1} [current_design]
set_property src_info {type:XDC file:1 line:3 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN L5 [get_ports A]
set_property src_info {type:XDC file:1 line:7 export:INPUT save:INPUT read:READ} [current_design]
set_property PACKAGE_PIN J5 [get_ports Y]
